# 切换生产环境地址使用
prod:
  host: 39.107.97.197
server:
  port: 8771

eureka:
  client:
    service-url:
      defaultZone: http://${prod.host}:8761/eureka/

spring:
  application:
    name: config
  profiles:
    active: dev
  rabbitmq:
    host: ${prod.host}
    port: 15672
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SpringCloud-Sell/config-repo.git
          username: Rushing0711
          password: Mt209@3
          basedir: /home/emon/saas/SpringCloud-Sell/config/basedir
management:
  endpoints:
    web:
      exposure:
        include: "*"
